### ISSUE TITLE
For the Community

### ISSUE THREAD

**Issue by wellwelwel** [mysqljs/aws-ssl-profiles#4]
- **Todo** 
  - [x] Create the _LICENSE_ (*)
  - [x] Create the _SECURITY.md_
  - [x] Create the _CONTRIBUTING.md_
  - [x] Create the _CODE_OF_CONDUCT.md_
  - [x] Improve the _README.md_ (depends on #5)

---

\* @sidorares, since this repository is under the **mysqljs** organization, what is the email for security reports and who is the main contributor to include in the license?

Can I copy these infos from **MySQL2**?

**Comment by sidorares** [comment]
this might be shared with mysqljs/mysql where long time maintainer was @dougwilson , would be good to have some input from him. I think it should be a union of mysql + mysql2 contacts

**Comment by dougwilson** [comment]
Yea, sounds good in general. I would say in the LICENSE you should at least put your name @wellwelwel since you are writing this project, and it makes sense. You can probably just leave it as that in reality, as there isn't even like code being copied from the mysql projects for this (it's just an object with the SSL certs in the end). But of course you can add the names from the project if you _really_ want to :)

For security contact, it's not like there is a mailing list or anything. What I found that I think is a good generic contact method I have been putting is the following, you are free to copy here:

```
Report security bugs by emailing the current owner(s) of <insert npm module name>.
This information can be found in the npm registry using the command `npm owner ls <insert npm module name>`.
If unsure or unable to get the information from the above, open an issue in the [project issue tracker](https://github.com/LINK_TO_ISSUE_TRACKER) asking for the current contact information.
```
